Bug3001: HeapStats CLI should report error without exception
HeapStats/heapstats pull request #38
Opened 2016-10-07 13:17 UTC by YaSuenag

This PR is for [Bug 3001](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3001) .

IMHO, it is difficult to catch all ```Throwable``` patterns. For example, to catch ```OutOfMemoryError``` is very difficult. 
So I propose to use uncaught exception handler. I've implemented to find root cause and to show localized message of it.
If you want to see stack trace for debugging, you can add ```-Ddebug``` to arguments of java.

Comments is appreciated.
Please review it.

2016-10-10 12:15 UTC, ykubota requested changes

2016-10-10 12:15 UTC, ykubota commented on analyzer/cli/src/main/java/jp/co/ntt/oss/heapstats/cli/CliMain.java
> +        // Find root cause of exception
We should write the reason why we find a root cause by using a while loop.

2016-10-10 12:15 UTC, ykubota commented on analyzer/cli/src/main/java/jp/co/ntt/oss/heapstats/cli/CliMain.java
> +        options.parse(args);
IMHO, I think that most users (who are not developers) want to read help messages instead of exception when they set wrong options.

2016-10-10 14:00 UTC, YaSuenag commented on analyzer/cli/src/main/java/jp/co/ntt/oss/heapstats/cli/CliMain.java
> +        // Find root cause of exception
Should I fix comment only?
(Do not I need to change the beavior?)

2016-10-10 14:07 UTC, ykubota commented on analyzer/cli/src/main/java/jp/co/ntt/oss/heapstats/cli/CliMain.java
> +        // Find root cause of exception
Yes, here's comment is so. Requested behavior change is described by above comment.

2016-10-11 12:47 UTC, YaSuenag commented
@ykubota Thank you for your comment!
Could you review again?

2016-10-11 13:15 UTC, ykubota approved these changes
👍

2016-10-11 13:50 UTC, closed without merging